# ==========================================
# MySQL Database Configuration (Cloud Ready)
# ==========================================
# Environment Variables ka use karein taaki password safe rahe
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# JWT Security Configuration
# ==========================================
# Yahan bhi environment variable ka use kiya hai
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==========================================
# OAuth2 Google Setup
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}